language: node_js

node_js:
  - v7

env:
  - PARALLEL_NODE=lint
  - PARALLEL_NODE=test

script:
  - npm run ${PARALLEL_NODE}

after_success:
  - curl -s https://codecov.io/bash | bash
  - git config --global user.email "auto_deploy@circleci.com"
  - git config --global user.name "CircleCI"
  - echo -e "cepave\n${NPM_PASSWD}\nrwu@cepave.com" | npm login
  - babel-node scripts/deploy.js

branches:
  except:
  - /v?\d+\.\d+\.\d+/