language: node_js
node_js:
  - v7
env:
  matrix:
    - TRAVIS_MATRIX=lint
    - TRAVIS_MATRIX=test
    - TRAVIS_MATRIX=build
  global:

script:
  - npm run $TRAVIS_MATRIX
after_success:
  - node scripts/deploy.js
branches:
  except:
    - /v?\d+\.\d+\.\d+/
